version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1

    steps:
      - checkout

      # Install dependencies
      - run: sudo apt update
      - run: sudo apt-get install libldap2-dev libpng-dev -y --no-install-recommends
      - run: sudo rm -rf /var/lib/apt/lists/*
      - run: sudo docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/
      - run: sudo docker-php-ext-install exif gd ldap mysqli pdo_mysql

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: COMPOSER_MEMORY_LIMIT=-1 composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      # lint files
      - run: ./vendor/bin/php-cs-fixer fix --dry-run --diff --verbose

      # run tests with phpunit
      - run: ./vendor/bin/phpunit tests -v
